In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, Model
import numpy as np
import librosa
from data_loading import extract_features
import os
import pickle
import random
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score


In [ ]:
# def create_base_network(input_shape):
#     """Shared feature extractor."""
#     model = tf.keras.Sequential([
#         layers.Conv1D(64, kernel_size=5, activation='relu', input_shape=input_shape),
#         layers.MaxPooling1D(pool_size=2),
#         layers.Conv1D(128, kernel_size=5, activation='relu'),
#         layers.GlobalMaxPooling1D(),
#         layers.Dense(128, activation='relu'),
#         layers.Dense(64, activation='relu')
#     ])
#     return model

# def create_siamese_network(input_shape):
#     base_network = create_base_network(input_shape)
    
#     # Two inputs for the Siamese network
#     input_a = layers.Input(shape=input_shape)
#     input_b = layers.Input(shape=input_shape)
    
#     # Shared embedding layers
#     embedding_a = base_network(input_a)
#     embedding_b = base_network(input_b)
    
#     # Distance metric (Euclidean Distance)
#     distance = layers.Lambda(lambda tensors: tf.sqrt(tf.reduce_sum(tf.square(tensors[0] - tensors[1]), axis=1, keepdims=True)))([embedding_a, embedding_b])
    
#     return Model(inputs=[input_a, input_b], outputs=distance)

import tensorflow as tf
from tensorflow.keras import layers, Model

def create_base_network(input_shape):
    """Shared feature extractor."""
    # model = tf.keras.Sequential([
    #     layers.Conv1D(64, kernel_size=5, activation=None, input_shape=input_shape),
    #     layers.BatchNormalization(),
    #     layers.LeakyReLU(alpha=0.1),
    #     layers.MaxPooling1D(pool_size=2),

    #     layers.Conv1D(128, kernel_size=5, activation=None, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    #     layers.BatchNormalization(),
    #     layers.LeakyReLU(alpha=0.1),
    #     layers.MaxPooling1D(pool_size=2),

    #     layers.Conv1D(256, kernel_size=5, activation=None, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    #     layers.BatchNormalization(),
    #     layers.LeakyReLU(alpha=0.1),
    #     layers.GlobalMaxPooling1D(),

    #     layers.Dense(128, activation=None, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    #     layers.BatchNormalization(),
    #     layers.LeakyReLU(alpha=0.1),
    #     layers.Dropout(0.5),

    #     layers.Dense(64, activation=None, kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    #     layers.BatchNormalization(),
    #     layers.LeakyReLU(alpha=0.1),
    #     layers.Dropout(0.5)
    # ])
    model=tf.keras.Sequential([
        layers.Dense(128, activation='leaky_relu', input_shape=input_shape),
        layers.Dropout(0.1),
        layers.Dense(128, activation='leaky_relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        layers.Dropout(0.1),
        layers.Dense(128, activation='leaky_relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
    ])
    return model

def create_siamese_network(input_shape):
    base_network = create_base_network(input_shape)
    
    # Two inputs for the Siamese network
    input_a = layers.Input(shape=input_shape)
    input_b = layers.Input(shape=input_shape)
    
    # Shared embedding layers
    embedding_a = base_network(input_a)
    embedding_b = base_network(input_b)

    # L2 normalization of embeddings
    embedding_a = layers.Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(embedding_a)
    embedding_b = layers.Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(embedding_b)

    # Distance metric (Euclidean Distance)
    # distance = layers.Lambda(lambda tensors: tf.sqrt(tf.reduce_sum(tf.square(tensors[0] - tensors[1]), axis=1, keepdims=True)))([embedding_a, embedding_b])
    distance = layers.Lambda(lambda tensors: tf.sqrt(tf.reduce_sum(tf.square(tensors[0] - tensors[1]), axis=1, keepdims=True) + 1e-8))([embedding_a, embedding_b])

    
    return Model(inputs=[input_a, input_b], outputs=distance)

# def contrastive_loss(y_true, y_pred, margin=1):
#     """Contrastive loss as a custom loss function."""
#     y_true = tf.cast(y_true, tf.float32)
#     squared_distance = tf.square(y_pred)
#     margin_distance = tf.square(tf.maximum(margin - y_pred, 0))
#     return tf.reduce_mean((1 - y_true) * squared_distance + y_true * margin_distance)
def contrastive_loss(y_true, y_pred, margin=1.0):
    """Contrastive loss as a custom loss function."""
    y_true = tf.cast(tf.reshape(y_true, (-1, 1)), tf.float32)  # Reshape to [batch_size, 1]
    squared_distance = tf.square(y_pred)
    margin_distance = tf.square(tf.maximum(margin - y_pred, 0))
    return tf.reduce_mean((1 - y_true) * squared_distance + y_true * margin_distance)


# 5. Data Preparation
def create_pairs(features, labels):
    """Generate pairs: (input_1, input_2, label)."""
    pairs = []
    pair_labels = []
    for i in range(len(features)):
        for j in range(i + 1, len(features)):
            # Create a positive pair (same speaker)
            if labels[i] == labels[j]:
                pairs.append((features[i], features[j]))
                pair_labels.append(0)  # Similar
            # Create a negative pair (different speakers)
            else:
                pairs.append((features[i], features[j]))
                pair_labels.append(1)  # Dissimilar
    # Shuffle the pairs and labels
    pairs, pair_labels = np.array(pairs), np.array(pair_labels)
    indices = np.random.permutation(len(pairs))
    pairs, pair_labels = pairs[indices], pair_labels[indices]
    return np.array(pairs), np.array(pair_labels)

# 6. Training
def train_siamese_network():
    # Load features and labels (replace with actual dataset)
    # features = np.random.rand(50, 100, 13)  # Mock data (1000 samples, 100 time steps, 13 features)
    # labels = np.random.randint(0, 10, size=50)  # Mock speaker IDs (10 speakers)
    siamese_net = create_siamese_network((250,14))
    print("Model Created")
    # print(siamese_net.summary())
    optimizer = tf.keras.optimizers.Adam(clipnorm=1.0)

    siamese_net.compile(optimizer=optimizer, loss=contrastive_loss, metrics=['accuracy'])
    
    for file in os.listdir("dataset"):
        if file.startswith("features_"):
            with open(f"dataset/{file}", "rb") as f:
                features = pickle.load(f)
            part_number=file.split(".")[0].split("_")[-1]
            with open(f"dataset/labels_part_{part_number}.pkl", "rb") as f:
                labels=pickle.load(f)
            print("Features Loaded")
            # Break Features and Labels into 10 parts
            features = np.array(features)
            labels = np.array(labels)
            
            # Normalize Features
            features = (features - np.mean(features, axis=0)) / (np.std(features, axis=0) + 1e-8)

            features = np.array_split(features, 10)
            labels = np.array_split(labels, 10)
            print("Features Split")
            for features_part, labels_part in zip(features, labels):
                # Create pairs
                pairs, pair_labels = create_pairs(features_part, labels_part)
                pairs = np.array(pairs)
                print("Pairs Created")
                # Split into train and test
                split = int(len(pairs) * 0.8)
                train_pairs, test_pairs = pairs[:split], pairs[split:]
                train_labels, test_labels = pair_labels[:split], pair_labels[split:]
                print("Train and Test Pairs Created")              
                history=siamese_net.fit(
                    [train_pairs[:, 0], train_pairs[:, 1]], train_labels,
                    validation_data=([test_pairs[:, 0], test_pairs[:, 1]], test_labels),
                    epochs=1,
                    batch_size=32,
                    verbose=0
                )
                print("Model Trained")
                siamese_net.save(f"weights/siamese_model_part_{part_number}.h5")
                print("Model Saved")
                
                # Infer on 10 test pairs
                n1=random.randint(0, len(test_pairs)//2)
                n2=n1+10
                test_pairs = test_pairs[n1:n2]
                test_labels = test_labels[n1:n2]
                test_distances = siamese_net.predict([test_pairs[:, 0], test_pairs[:, 1]])
                test_loss=contrastive_loss(test_labels, test_distances)
                # roc_auc = roc_auc_score(test_labels, test_distances)
                threshold = 0.1
                test_predictions=[]
                for t in test_distances:
                    test_predictions.append(0 if t.mean()<threshold else 1)
                # test_predictions = (test_distances > threshold).astype(int)
                # test_predictions = test_distances.ravel() < threshold
                
                # precision=precision_score(test_labels, test_predictions)
                # recall=recall_score(test_labels, test_predictions)
                # f1=f1_score(test_labels, test_predictions)
                
                test_predictions = np.squeeze(test_predictions)  # Remove extra dimensions
                
                # print(test_distances, test_labels, test_predictions)
                print(test_labels, test_predictions)
                # print(test_distances.shape, test_labels.shape, test_predictions.shape)
                print(f"Test Loss: {test_loss}")
                print("Test Accuracy: ", np.mean(test_predictions == test_labels))
                # print(f"ROC AUC: {roc_auc}")
                # print(f"Precision: {precision}")
                # print(f"Recall: {recall}")
                # print(f"F1 Score: {f1}")
                # print("Model Evaluated")
                
                
    return siamese_net

In [66]:
# 7. Run Training
model = train_siamese_network()

Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[1 1 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.29887279868125916
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.1983578573904197e-08
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 1 1 0 0 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.29754820466041565
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[0 0 0 0 1 0 1 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2901046872138977
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[0 0 0 0 0 0 1 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2937086820602417
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0743773515287103e-07
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.351005605305545e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[0 1 1 0 0 1 1 1 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5650272965431213
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[1 0 1 1 0 0 1 1 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5917415022850037
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[0 1 1 0 0 1 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.48113155364990234
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[1 0 0 0 1 0 1 1 0 1] [1 0 0 0 1 0 1 0 0 0]
Test Loss: 0.43241310119628906
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 9.70456312643364e-07
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.1301210633973824e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09709327667951584
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[1 0 1 0 0 1 1 1 0 0] [0 0 0 0 0 1 1 0 1 1]
Test Loss: 0.41404300928115845
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 1 1 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.38037291169166565
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 1 0 0 0 0 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.287894070148468
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[1 0 1 1 0 0 0 1 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.47692909836769104
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 1 0 1 1 1 0 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.584073543548584
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 0 1 0 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3861786127090454
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[0 0 0 1 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09680323302745819
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.4647400209687476e-07
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.1144504874494032e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[0 0 0 0 0 0 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2931174039840698
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 1 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09540513902902603
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[1 0 0 0 0 1 0 0 1 0] [1 1 0 0 0 1 0 0 0 0]
Test Loss: 0.26412108540534973
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 0 0 1 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.098518505692482
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 1 0 1 0 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.38903144001960754
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 1 1 1 0 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3937714099884033
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[1 1 0 0 1 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.38652968406677246
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 4.62753541796701e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.5536350872480398e-08
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0001024008943205e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09949781745672226
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 1 0 1 0 0 1 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5812249779701233
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[1 1 0 0 1 1 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.48643070459365845
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[1 1 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.19401687383651733
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 1 1 1 1 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.49529898166656494
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[0 1 0 1 1 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3882541358470917
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 1 0 0 0 1 0 0 0 0] [0 0 0 1 0 0 0 1 0 0]
Test Loss: 0.1812412142753601
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[1 1 1 1 0 1 1 0 1 0] [0 0 0 0 0 1 0 0 0 0]
Test Loss: 0.6646199226379395
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 6.519944406591094e-08
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[0 1 0 1 1 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.38157394528388977
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 1 1 1 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.39563876390457153
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[1 0 1 0 1 1 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.48829689621925354
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[0 0 0 0 0 0 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.1971079707145691
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[1 1 1 1 0 0 0 1 1 1] [0 0 1 1 0 1 0 0 0 0]
Test Loss: 0.6168623566627502
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 0 1 0 0 1 0 1 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.39494505524635315
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09960674494504929
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 0 0 0 0 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09946880489587784
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 1 0 0 0 1 0 0 1 1] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.26945704221725464
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[0 1 1 0 0 1 0 0 1 0] [0 0 0 0 0 0 0 0 1 0]
Test Loss: 0.3671890199184418
Test Accuracy:  0.7
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0007202035922091e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[1 1 1 0 1 1 0 0 0 0] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.2753532826900482
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
[1 1 0 0 0 0 0 0 1 1] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.25462737679481506
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 0 0 0 1 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.29335975646972656
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[0 0 0 0 0 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09796158969402313
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.0002351141010876745
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0848145137742904e-07
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[1 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09951445460319519
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 1 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.19441990554332733
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 5.868566859135171e-07
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0556481910839466e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.606589077913668e-05
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 0 1 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.19737549126148224
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[0 1 0 1 0 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.26903802156448364
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 1 1 0 0 1 0 1 1 1] [1 1 0 0 0 1 0 1 0 1]
Test Loss: 0.48839667439460754
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[1 0 1 0 0 0 1 0 1 0] [0 0 1 0 0 0 0 0 0 0]
Test Loss: 0.3499448299407959
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[0 1 0 1 0 0 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4624658524990082
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[1 0 0 1 0 1 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4458484649658203
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 0 1 0 1 0 0 0] [0 0 0 1 0 0 1 1 1 0]
Test Loss: 0.25614985823631287
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.2636666471953504e-05
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 3.491141171707568e-07
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[0 0 0 0 0 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09400228410959244
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[1 1 1 0 1 0 0 1 0 1] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.43874794244766235
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 0 0 1 1 0 1 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4695935845375061
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[0 1 0 1 0 0 1 1 1 0] [0 1 0 1 0 1 1 1 0 0]
Test Loss: 0.4102889597415924
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[0 1 1 0 1 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3737376928329468
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 0 0 1 1 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3946342468261719
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 0 1 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.19349075853824615
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.00026765899383462965
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.8382544908490672e-07
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.2074796273964239e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[0 0 1 0 1 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2948387563228607
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 0 0 0 0 0 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.19876450300216675
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 1 1 0 1 0 0 0] [0 0 0 0 0 0 1 0 0 0]
Test Loss: 0.26716944575309753
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 1 0 1 0 1 0 1 0 0] [0 0 0 1 0 0 0 0 0 0]
Test Loss: 0.3535971939563751
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[1 1 1 1 1 0 0 0 0 0] [1 1 1 1 1 1 1 1 0 0]
Test Loss: 0.38041236996650696
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 1 1 0 1 1 0 0 0] [0 1 0 0 0 0 1 0 0 0]
Test Loss: 0.35309121012687683
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[1 1 1 0 1 0 0 0 1 1] [0 0 0 0 0 0 1 1 0 0]
Test Loss: 0.5298762321472168
Test Accuracy:  0.2
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 0 1 1 0 0 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5970757007598877
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.9860027578033623e-07
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 1 0 0 0 0 0] [0 1 1 0 1 0 1 1 0 1]
Test Loss: 0.0913611426949501
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 0 1 1 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2702435553073883
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 1 1 1 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3740130662918091
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[1 0 0 1 0 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2749909460544586
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 1 0 0 1 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2623046040534973
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 1 0 0 0 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.18018987774848938
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[1 0 1 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2858961224555969
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 3.8424754166044295e-05
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.1746925210331938e-08
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.0002154660071483e-08
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09990076720714569
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 1 1 1 0 0 0 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4912980794906616
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[0 0 0 0 1 0 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2874308228492737
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 1 1 0 0 0 1 1 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5791400074958801
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[1 0 1 1 0 1 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4852133095264435
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 1 1 0 1 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5821425318717957
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[1 0 0 0 0 0 1 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2964296340942383
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[1 0 1 1 0 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.38547706604003906
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 0 1 1 1 0 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4607310891151428
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 1 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2948923408985138
Test Accuracy:  0.7
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 1 1 1 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.587472140789032
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 0 0 0 1 1 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.594140350818634
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 1 1 0 1 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5729221105575562
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 1 0 1 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4921199679374695
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 1 1 1 1 1 0 1 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.8976778984069824
Test Accuracy:  0.1
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 1 0 1 0 1 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.5958747863769531
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 1 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.199209064245224
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 1 0 1 0 1 1 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.49551817774772644
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 0 1 1 0 0 1 1 1 1] [0 0 0 0 0 1 0 0 0 1]
Test Loss: 0.6132447719573975
Test Accuracy:  0.3
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.098324102917104e-06
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[0 0 0 0 0 0 0 0 0 0] [1 1 0 0 1 1 1 0 1 0]
Test Loss: 0.013200724497437477
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 0 0 1 0 1 0] [1 1 0 0 1 1 1 1 1 1]
Test Loss: 0.17522254586219788
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[0 1 0 1 1 1 0 1 1 1] [1 1 1 1 1 0 1 1 1 1]
Test Loss: 0.47528892755508423
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[0 1 0 0 0 0 0 1 1 1] [0 1 0 0 0 0 0 1 0 1]
Test Loss: 0.344888836145401
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 1 0 1 1 0 0 0] [0 1 0 1 0 0 0 0 0 0]
Test Loss: 0.26760756969451904
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 1 1 1 1 0 1 0 1 0] [1 1 1 1 1 0 1 0 0 0]
Test Loss: 0.5517911314964294
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 1 0 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.1815406084060669
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 0 1 1 1 0 0 1 0 1] [1 0 1 1 1 0 0 1 1 1]
Test Loss: 0.44980698823928833
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 1 1 1 1 0 1 1 0 1] [1 1 0 1 0 0 1 1 0 1]
Test Loss: 0.5325687527656555
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.001791460206732154
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 1 1 1 1 1 1 0] [1 1 1 1 1 0 1 0 1 1]
Test Loss: 0.453169047832489
Test Accuracy:  0.4
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 1 0 0 0 0 0 1 0] [1 1 1 1 1 1 1 1 0 1]
Test Loss: 0.16767127811908722
Test Accuracy:  0.1
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 1 0 1 1 1 1 1 0 0] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.37567847967147827
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 1 0 1 0 1 0] [0 1 0 1 1 1 1 1 1 0]
Test Loss: 0.2457645833492279
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 4.5293681978364475e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[0 1 0 1 0 0 0 1 0 0] [1 1 0 0 0 1 0 1 0 0]
Test Loss: 0.2495831698179245
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[1 1 0 0 0 1 0 0 1 1] [0 1 1 0 1 0 0 1 0 0]
Test Loss: 0.40538275241851807
Test Accuracy:  0.3
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[0 0 0 1 0 0 1 0 0 0] [0 0 1 1 0 0 1 0 0 0]
Test Loss: 0.17596551775932312
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[1 1 0 1 1 1 0 0 1 0] [0 0 0 0 1 0 0 0 0 0]
Test Loss: 0.5298795104026794
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[1 1 0 1 1 0 0 1 0 1] [1 1 0 1 1 0 1 1 0 1]
Test Loss: 0.4862639904022217
Test Accuracy:  0.9
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.664193405304104e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 0 1 0 1 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.39329051971435547
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 1 0 0 1 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.274039089679718
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 0 1 0 0 0 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.36665669083595276
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 1 0 1 1 1 0 1 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.4585384130477905
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.09953849762678146
Test Accuracy:  0.9
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[0 0 0 0 1 0 1 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2803460359573364
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 3.868508429150097e-06
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[0 0 0 0 0 0 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.18049541115760803
Test Accuracy:  0.8
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 0 0 1 1 0 1 0 1 0] [1 0 0 1 1 0 1 0 1 0]
Test Loss: 0.40278708934783936
Test Accuracy:  1.0
Features Loaded
Features Split
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 1.5792662111380196e-07
Test Accuracy:  1.0
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 0 1 0 0 0 0 1 0 1] [0 0 0 0 0 0 0 1 0 0]
Test Loss: 0.36759939789772034
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[1 0 0 0 0 1 0 1 1 0] [1 0 0 0 0 0 0 0 0 0]
Test Loss: 0.3606414794921875
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 1 1 0 0 0 0] [0 0 0 0 0 0 0 1 0 0]
Test Loss: 0.1872432380914688
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[0 0 1 1 1 1 1 0 0 1] [0 0 0 0 0 0 1 0 0 0]
Test Loss: 0.5334932804107666
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 0 0 0 0 1 1 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.2781900465488434
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[0 0 1 0 1 0 1 1 1 0] [1 1 1 1 1 1 1 1 1 1]
Test Loss: 0.30320221185684204
Test Accuracy:  0.5
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[1 0 1 0 0 0 1 0 0 1] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.380710244178772
Test Accuracy:  0.6
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[1 0 0 0 1 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 0.28462186455726624
Test Accuracy:  0.7
Pairs Created
Train and Test Pairs Created


Model Trained
Model Saved
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
Test Loss: 2.3348918603005586e-06
Test Accuracy:  1.0
